---
chips:
 - name: "ML Chip"
   number_of_apartments: 47
   number_of_streets: 128
   apartment_spacing: 205.2
   street_spacing: 194.4
   chip_width: 26000.0
   chip_height: 9500.0 
 - name: "ML Chip 01"
   number_of_apartments: 47
   number_of_streets: 128
   apartment_spacing: 205.2
   street_spacing: 194.4
   chip_width: 26000.0
   chip_height: 9500.0
 - name: "KL Chip"
   number_of_apartments: 34
   number_of_streets: 128
   apartment_spacing: 280.6
   street_spacing: 194.4
   chip_width: 26000.0
   chip_height: 9500.0
drugs:
 - "Control"
 - "Quizartinib" 
 - "Imatinib"
 - "DRUG A"
 - "Nilotinib"
 - "Dasatinib"
 - "Ponatinib"
cells:
 - "MOLM13"
 - "PC9"
 - "CELL A"
 - "K562"
 - "K562S"
 - "K562R"
 - "OCI1"
 - "MV411"
 - "MOLM"
origins:
 - "ATCC"
 - "Sigma"
 - "CCF (Duke)"