BFF: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0
DAP: 
  - shutter: 0
    1: 0
    2: 0
    3: 0
    4: 20
GFP: 
  - shutter: 1
    1: 0
    2: 50
    3: 0
    4: 0
TXR: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0
CY5: 
  - shutter: 0
    1: 0
    2: 0
    3: 50
    4: 0